
'use client';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import ReactMarkdown from 'react-markdown';

type ReportModalProps = {
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
  report: string;
};

export function ReportModal({ isOpen, setIsOpen, report }: ReportModalProps) {
  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>AI Portfolio Report</DialogTitle>
          <DialogDescription>
            A detailed analysis of your portfolio, generated by Gemini AI.
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="max-h-[60vh] pr-6">
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown 
                components={{
                    h3: ({node, ...props}) => <h3 className="text-lg font-semibold mt-4 mb-2 text-primary" {...props} />,
                    strong: ({node, ...props}) => <strong className="font-bold text-primary" {...props} />,
                    a: ({node, ...props}) => <a className="text-primary hover:underline" target="_blank" rel="noopener noreferrer" {...props} />,
                    ul: ({node, ...props}) => <ul className="list-disc pl-5 space-y-1" {...props} />,
                    li: ({node, ...props}) => <li className="mb-1" {...props} />,
                }}
              >
                  {report}
              </ReactMarkdown>
            </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
